import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar";
import "./globals.css";
import Background from "../components/Background";
import Providers from "./providers";
import Menu from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#eccbb1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" text-orange-200 ">
        <Background />
        <Providers>
          <div className="flex flex-col min-h-screen">
            <header>
              <NavBar />
              <Menu />
            </header>
            <main className="grow min-h-full flex justify-center ml-20">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
